feat: generate app using `rails new`
uiowahjmjohnsonselt2023/selt2023-final-project-team-001 pull request #1
Opened 2023-11-02 15:11 UTC by evfinkn

Use `--minimal` flag since things like `ActionMailer` likely won't be useful for our app and can always be added later.

2023-11-02 16:21 UTC, evfinkn commented
In hindsight, `ActionMailer` actually could be useful for emailing other users, but again, we shouldn't add it until it's needed.

2023-11-02 18:03 UTC, powersaudrey25 commented on Gemfile
I believe we will need to specify to use pg for heroku. 
group :production do
  gem 'pg' # for Heroku deployment
  gem 'rails_12factor'
end

2023-11-03 16:49 UTC, evfinkn commented on Gemfile
I just read [Heroku's Rails 7 guide](https://devcenter.heroku.com/articles/getting-started-with-rails7), and they strongly recommend using Postgres everywhere:

> Heroku highly recommends using PostgreSQL locally during development. Maintaining parity between development and deployment environments prevents introducing subtle bugs due to the differences in environments.

Do we think we should use Postgres in production or in every environment?

Also, we talked about it in the meeting, but for future reference: `rails_12factor` isn't needed for Rails 5.x and later.

2023-11-03 16:55 UTC, powersaudrey25 commented on Gemfile
We can try it. I don't think the implementation will be any different.

2023-11-04 14:02 UTC, kesslerjohn commented on Gemfile
I agree - I don't see any downsides to using Postgres in every environment as long as everyone's local environment supports it

2023-11-05 15:33 UTC, evfinkn commented
For `pre-commit` to work, I had to do `rbenv global 3.1.3` since `pre-commit` defaults to the system Ruby version. See [pre-commit issue #1930](https://www.github.com/pre-commit/pre-commit/issues/1930#issuecomment-852169116):

> ruby defaults to using your system installation (for speed, and for windows)

Specifying `language_version` installs an entire new Ruby instance which isn't ideal (and that quote makes it seem like it wouldn't work for Windows?). Is this okay with everyone?

2023-11-05 17:03 UTC, powersaudrey25 commented
> For `pre-commit` to work, I had to do `rbenv global 3.1.3` since `pre-commit` defaults to the system Ruby version. See [pre-commit issue #1930](https://www.github.com/pre-commit/pre-commit/issues/1930#issuecomment-852169116):
> 
> > ruby defaults to using your system installation (for speed, and for windows)
> 
> Specifying `language_version` installs an entire new Ruby instance which isn't ideal (and that quote makes it seem like it wouldn't work for Windows?). Is this okay with everyone?

I think this is okay. If I am understanding correctly, we just have to make sure our global version of ruby is 3.1.3 for pre-commit to work?

2023-11-05 17:03 UTC, powersaudrey25 approved these changes

2023-11-05 17:18 UTC, powersaudrey25 requested changes
Oh wait, we also need the SimpleCov gem I don't see it in the gemfile

2023-11-05 20:42 UTC, evfinkn commented
> > For `pre-commit` to work, I had to do `rbenv global 3.1.3` since `pre-commit` defaults to the system Ruby version. See [pre-commit issue #1930](https://www.github.com/pre-commit/pre-commit/issues/1930#issuecomment-852169116):
> > > ruby defaults to using your system installation (for speed, and for windows)
> > 
> > 
> > Specifying `language_version` installs an entire new Ruby instance which isn't ideal (and that quote makes it seem like it wouldn't work for Windows?). Is this okay with everyone?
> 
> I think this is okay. If I am understanding correctly, we just have to make sure our global version of ruby is 3.1.3 for pre-commit to work?

Correct (in addition to installing it). I added `pre-commit` installation instructions and PostgreSQL installation instructions for macOS with Homebrew to the README.

2023-11-05 20:44 UTC, powersaudrey25 approved these changes

2023-11-05 20:45 UTC, merged