Update look of the website
uiowahjmjohnsonselt2023/selt2023-final-project-team-001 pull request #24
Opened 2023-11-21 19:27 UTC by evfinkn

- Creates a main layout containing a navigation bar and footer.
  - The navbar has links to the home page, products page, each category (all of which currently go nowhere), and the login page. When the user is logged in, the "Login" button is instead a dropdown containing a link to their profile and to logout. There's also a search bar (which currently does nothing), and the active page's link in the navbar is brighter than the other links.
  - The footer contains links to the home page as well as dead links to the features page, FAQs page, and about page.
- Styles the login page.
  - This includes adding a link to the signup page under the "Login" button. Additionally, a "Remember me" checkbox and "Forgot password?" link have been added, but they currently do nothing.
- Styles the signup page.
  - This includes adding a link to the login page under the "Signup" button.
- Styles the flash.
  - Besides a new look, there's now a dismiss button.

In order to do all of this styling, some refactoring had to be done:

- The `current_user` attribute of `ApplicationController` was moved to the new `Current` class so that it could be accessed from views.
- Setting `Current.user` and redirecting to the login page when not logged-in are now two different methods.
- The `importmap-rails` was added gem in order to use Bootstrap's JavaScript functions, enabling dropdowns to function properly.
- The `turbo-rails` and `stimulus-rails` gems were added to speed up the website.
- The `inline_svg` gem was added along with three SVG icons for use in flash messages.
- Helpers were made to separate most of the logic from the views as well as to make elements reusable.

Here is what the updated pages look like:

![styled-home-page-with-flash](https://github.com/uiowahjmjohnsonselt2023/selt2023-final-project-team-001/assets/6924485/ed604769-aa98-4262-8586-884e9911dff0)
![styled-login-page](https://github.com/uiowahjmjohnsonselt2023/selt2023-final-project-team-001/assets/6924485/1c5f1977-ed23-4e29-af41-15c00e5ef2ee)
![styled-signup-page](https://github.com/uiowahjmjohnsonselt2023/selt2023-final-project-team-001/assets/6924485/c2c12f76-d364-492f-bcd9-a73ff3988715)

2023-11-21 21:03 UTC, powersaudrey25 commented
Looks awesome! The checkout page will be hosted at "/checkout", we should probably put that in the navbar

2023-11-22 03:43 UTC, blhohmann requested changes
Looks really professional, phenomenal work Evan.

The refactors also will save us lots of time, good touch.

I added a suggestion for readding hovering to the dropdowns because I personally like hovering to show dropdown contents on the navbar. If you removed it because you think the hover wouldn't be a good fit that's fine, but I think it improves the usability of the website. Let me know what you think.

2023-11-22 03:43 UTC, blhohmann commented on app/assets/stylesheets/application.scss
>  }
```suggestion
}
.dropdown-menu {
    display: none;
}

.dropdown:hover .dropdown-menu {
    display: block;
}
```

2023-11-22 04:31 UTC, evfinkn commented on app/assets/stylesheets/application.scss
>  }
I didn't realize I removed it, good catch!

2023-11-22 07:57 UTC, blhohmann approved these changes

2023-11-22 14:20 UTC, merged