Checkout items
uiowahjmjohnsonselt2023/selt2023-final-project-team-001 pull request #27
Opened 2023-11-22 21:48 UTC by powersaudrey25

This pr includes code for the following user stories:
https://www.pivotaltracker.com/story/show/186382467
https://www.pivotaltracker.com/story/show/186382461

### Main features (non UI)

1. A cart model - essentially a join table where each entry is {user id, product id, quantity}
2. Associations between users, carts, and products
3. Upon purchase of items a user's cart is set back to being empty and each product has its quantity decreased in the products table --> _we will need to discuss how to handle when the quantity becomes 0, as of right now we don't allow a product to have 0 quantity in the products table_
4. Currently, there is no validation for the fields besides being required for the payment form as we do not actually need to process payments. No payment, or shipping address info is being saved in our db.

### Main features (UI)
A user may adjust the quantity of their items and/or remove them from their cart
<img width="500" alt="Screenshot 2023-11-22 at 2 30 16 PM" src="https://github.com/uiowahjmjohnsonselt2023/selt2023-final-project-team-001/assets/57544141/5d23d218-2316-420b-8a2e-ac53f1c30dd0">
<img width="500" alt="Screenshot 2023-11-22 at 2 32 08 PM" src="https://github.com/uiowahjmjohnsonselt2023/selt2023-final-project-team-001/assets/57544141/25814802-c2d3-49c1-a8f2-5343a167e9ad">
<img width="500" alt="Screenshot 2023-11-22 at 2 36 07 PM" src="https://github.com/uiowahjmjohnsonselt2023/selt2023-final-project-team-001/assets/57544141/cef1e4bc-0566-4fd2-b1fc-b8da77a5d095">
<img width="500" alt="Screenshot 2023-11-22 at 3 40 08 PM" src="https://github.com/uiowahjmjohnsonselt2023/selt2023-final-project-team-001/assets/57544141/4d59b7d5-274f-4fff-8be3-5b92e6389e9e">

A user can fill out the required fields to purchase their items, their choice in shipping dynamically changes their total
<img width="500" alt="Screenshot 2023-11-22 at 3 43 53 PM" src="https://github.com/uiowahjmjohnsonselt2023/selt2023-final-project-team-001/assets/57544141/84df5500-026f-4e09-8b99-ec4ddd3da77e">
<img width="500" alt="Screenshot 2023-11-22 at 3 43 59 PM" src="https://github.com/uiowahjmjohnsonselt2023/selt2023-final-project-team-001/assets/57544141/6a9c7c83-ec13-48fa-a4de-3e990ed8384d">
<img width="500" alt="Screenshot 2023-11-22 at 3 43 59 PM" src="https://github.com/uiowahjmjohnsonselt2023/selt2023-final-project-team-001/assets/57544141/e1b75be2-33f4-4d37-8bc9-486d64b96494">
<img width="500" alt="Screenshot 2023-11-22 at 3 46 05 PM" src="https://github.com/uiowahjmjohnsonselt2023/selt2023-final-project-team-001/assets/57544141/c346080a-3601-4dbb-9429-c354cf4c6f96">

2023-11-22 23:59 UTC, blhohmann commented
In the future, should we add tax to the total, for example, pick the state they say they're from and add that to the total? Idk if it has to be in this sprint.

2023-11-23 00:11 UTC, blhohmann requested changes
Great work! I really like the look of the page and the shipping is a good touch especially with it automatically updating the total.

I added some reviews, I also think it may be worth adding validation to the fields or doing something like making states a dropdown with each state, but I don't think it's a dealbreaker.

2023-11-23 00:16 UTC, powersaudrey25 commented
> In the future, should we add tax to the total, for example, pick the state they say they're from and add that to the total? Idk if it has to be in this sprint.

definitely could! Just wasn't a priority right now since payments don't actually matter

2023-11-23 00:18 UTC, powersaudrey25 commented on app/controllers/checkouts_controller.rb
> +
Yes that is good idea, I can implement that!

2023-11-23 00:19 UTC, powersaudrey25 commented on app/controllers/checkouts_controller.rb
> +    flash[:success] = "Item quantity updated successfully!"
Good catch, honestly doesn't even make sense to display a flash if you update the quantity to the same one

2023-11-23 01:16 UTC, blhohmann commented
> > In the future, should we add tax to the total, for example, pick the state they say they're from and add that to the total? Idk if it has to be in this sprint.
> 
> definitely could! Just wasn't a priority right now since payments don't actually matter

That makes sense, I say don't worry about it then.

2023-11-23 01:28 UTC, powersaudrey25 commented on app/controllers/checkouts_controller.rb
> +
How about this? I check if a user who is not logged in tries to navigate to the cart they will immediately by redirected to the log in page. 

<img width="500" alt="Screenshot 2023-11-22 at 7 27 09 PM" src="https://github.com/uiowahjmjohnsonselt2023/selt2023-final-project-team-001/assets/57544141/33f1e9d4-c960-4538-a766-0733e5999f55">

2023-11-23 01:35 UTC, blhohmann commented on app/controllers/checkouts_controller.rb
> +
That is a good solution too. It will still save their cart after they log in right, I forgot to test that.

2023-11-23 01:42 UTC, powersaudrey25 commented on app/controllers/checkouts_controller.rb
> +
With the way that the cart model is set up, in order for a user to add an item to their cart they have to log in. I was thinking that users could browse products without logging in but if they click add to cart or try to go to checkout, they will be prompted to log in. I couldn't think of a way to temporarily store a non-logged in user's items. I'm open to ideas though!

2023-11-23 01:44 UTC, blhohmann commented on app/controllers/checkouts_controller.rb
> +
Got it, I say your solution is definitely the way to go then, if they can't add items to their cart they shouldn't be able to view the cart.

If we change our mind I think we could do something like store the products to add to the carts id in session, but I don't think it's worth the effort tbh. I say we stick with your way.

2023-11-23 01:58 UTC, blhohmann approved these changes
Looks great! Thanks for the changes.

2023-11-23 02:00 UTC, merged