Dynamic products page
uiowahjmjohnsonselt2023/selt2023-final-project-team-001 pull request #30
Opened 2023-11-22 23:25 UTC by kesslerjohn

This creates a products page allowing users to sort products by name, price, and date posted, with placeholder links for viewing the detail page for each product. There are also placeholder filters which can be implemented when product tags are available. 
Also contains a fix to a seller registration bug that did not save a registered seller's new status to the database.

2023-11-23 00:32 UTC, blhohmann commented
On my end when checking out this branch I get a previous test failing.

104 examples, 1 failure, 11 pending

Failed examples:

rspec ./spec/controllers/products_controller_spec.rb:20 # ProductsController when passing in a product that doesn't exist GET #show redirects to the home page

2023-11-23 01:08 UTC, kesslerjohn commented
Oops - I think this is because I don't have seller or product factories on this branch. I'll see if I can resolve the conflicts to rebase on main and check whether that resolves it.

2023-11-23 01:13 UTC, blhohmann requested changes
Looks cool, I think we just have some changes to add and we should be good. I think also Audrey said you should add adding products to the cart in this pull request. Additionally, I left a comment outside of this review on accident that I would also appreciate your response to, thanks!

2023-11-23 01:13 UTC, blhohmann commented on app/views/products/index.html.erb
> +<%= bootstrap_form_with model: @products, url: products_path, method: :post, local: true do |f| %>
I don't think these should be checkboxes, I think they should be radio buttons because it doesn't make sense for Price high to low and Price low to high to both be selected for example.

2023-11-23 01:13 UTC, blhohmann commented on db/seeds/development.rb
> +# Profile.insert_all(
I believe we want to keep profiles being inserted for development testing

2023-11-23 01:13 UTC, blhohmann commented on app/views/products/index.html.erb
> +        <td><%= link_to product.name, "/show" %></td>
I believe this line should redirect to products/id otherwise it will give a 404 as just /show doesn't exist
```suggestion
        <td><%= link_to product.name, product_path(product.id) %></td>
```

2023-11-23 01:19 UTC, blhohmann commented
I also think we may be showing private products or something on the all products page, for example when I click Sleek Linen Shirts it tries to go to /products/62 but it redirects and it says  You don't have permission to view that product. I think products like that shouldn't be shown.

2023-11-23 01:46 UTC, kesslerjohn commented on db/seeds/development.rb
> +# Profile.insert_all(
Fixed!

2023-11-23 03:04 UTC, kesslerjohn commented on app/views/home/index.html.erb
> +<%= link_to "Shop", products_path %>
When you say rebase main into this branch, do you mean rebase this on top of main? Or checkout main and rebase on this branch?

2023-11-23 03:10 UTC, kesslerjohn commented on app/views/products/index.html.erb
> +        <td><%= link_to product.name, "/show" %></td>
Fixed on [6e30c82](https://github.com/uiowahjmjohnsonselt2023/selt2023-final-project-team-001/pull/30/commits/6e30c8284e1f2664113a706828926d91cbc7c81e)

2023-11-23 03:13 UTC, kesslerjohn commented on app/views/products/index.html.erb
> +<%= bootstrap_form_with model: @products, url: products_path, method: :post, local: true do |f| %>
Sounds good - I removed them completely for the time being but I'll add them as radio buttons when completing the user story for filtering.

2023-11-23 03:14 UTC, kesslerjohn commented on app/views/products/index.html.erb
> +  <%= f.check_box :filter_2, label: 'Price (high to low)' %>
Yeah, this resulted from me linking to the wrong path in the Apply button. I commented this below too, but I removed the buttons for now and will add them back in a separate branch for the filtering story.

2023-11-23 03:49 UTC, blhohmann commented on app/views/home/index.html.erb
> +<%= link_to "Shop", products_path %>
Maybe I'm not using the right words, I basically mean like merge the new changes of main into here, just I think the professor prefers rebasing. The way I do it is like this
```
git checkout main
git pull
git checkout your_branches_name
git rebase main
git push origin your_branches_name --force
```

2023-11-23 03:50 UTC, blhohmann commented on app/views/products/index.html.erb
> +  <%= f.check_box :filter_2, label: 'Price (high to low)' %>
Thanks!

2023-11-23 03:51 UTC, blhohmann commented on app/views/products/index.html.erb
> +<%= bootstrap_form_with model: @products, url: products_path, method: :post, local: true do |f| %>
Perfect, thanks!

2023-11-23 03:51 UTC, kesslerjohn commented on app/controllers/sessions_controller.rb
> +    end
Added this!

2023-11-23 03:54 UTC, kesslerjohn commented on app/views/home/index.html.erb
> +<%= link_to "Shop", products_path %>
Okay cool - that's what I assumed but I wanted to make sure I understood. I'm working on resolving conflicts to rebase it right now, I'll make a post in Teams and here when it's done.

2023-11-23 04:43 UTC, kesslerjohn commented
> On my end when checking out this branch I get a previous test failing.
> 
> 104 examples, 1 failure, 11 pending
> 
> Failed examples:
> 
> rspec ./spec/controllers/products_controller_spec.rb:20 # ProductsController when passing in a product that doesn't exist GET #show redirects to the home page

I still get this error when I checkout main and pull. Is it running fine for you locally? 
I'll have to finish rebasing tomorrow - sorry for the delay. I should be ready to merge before Friday morning.

2023-11-23 05:00 UTC, blhohmann commented
> > On my end when checking out this branch I get a previous test failing.
> > 104 examples, 1 failure, 11 pending
> > Failed examples:
> > rspec ./spec/controllers/products_controller_spec.rb:20 # ProductsController when passing in a product that doesn't exist GET #show redirects to the home page
> 
> I still get this error when I checkout main and pull. Is it running fine for you locally? I'll have to finish rebasing tomorrow - sorry for the delay. I should be ready to merge before Friday morning.

I get this when running it locally after checking out main and pulling.
Finished in 16.96 seconds (files took 11.67 seconds to load)
114 examples, 0 failures, 13 pending

Coverage report generated for RSpec to /mnt/c/Users/blake/selt2023-final-project-team-001/coverage. 1063 / 1084 LOC (98.06%) covered.

One thing of note, is I also do 
```
bin/rails db:drop
bin/rails db:create
bin/rails db:migrate
bin/rails db:seed
```

2023-11-23 05:01 UTC, blhohmann commented on .gitignore
> +/coverage/*
Also I think we are meant to keep coverage for grading purposes.

2023-11-23 05:21 UTC, blhohmann commented
> > > On my end when checking out this branch I get a previous test failing.
> > > 104 examples, 1 failure, 11 pending
> > > Failed examples:
> > > rspec ./spec/controllers/products_controller_spec.rb:20 # ProductsController when passing in a product that doesn't exist GET #show redirects to the home page
> > 
> > 
> > I still get this error when I checkout main and pull. Is it running fine for you locally? I'll have to finish rebasing tomorrow - sorry for the delay. I should be ready to merge before Friday morning.
> 
> I get this when running it locally after checking out main and pulling. Finished in 16.96 seconds (files took 11.67 seconds to load) 114 examples, 0 failures, 13 pending
> 
> Coverage report generated for RSpec to /mnt/c/Users/blake/selt2023-final-project-team-001/coverage. 1063 / 1084 LOC (98.06%) covered.
> 
> One thing of note, is I also do
> 
> ```
> bin/rails db:drop
> bin/rails db:create
> bin/rails db:migrate
> bin/rails db:seed
> ```

Wait I just tried again, I hadn't pulled correctly, now it also fails that test. Strange... Must have been introduced elsewhere.

2023-11-23 05:45 UTC, blhohmann commented
> > > > On my end when checking out this branch I get a previous test failing.
> > > > 104 examples, 1 failure, 11 pending
> > > > Failed examples:
> > > > rspec ./spec/controllers/products_controller_spec.rb:20 # ProductsController when passing in a product that doesn't exist GET #show redirects to the home page
> > > 
> > > 
> > > I still get this error when I checkout main and pull. Is it running fine for you locally? I'll have to finish rebasing tomorrow - sorry for the delay. I should be ready to merge before Friday morning.
> > 
> > 
> > I get this when running it locally after checking out main and pulling. Finished in 16.96 seconds (files took 11.67 seconds to load) 114 examples, 0 failures, 13 pending
> > Coverage report generated for RSpec to /mnt/c/Users/blake/selt2023-final-project-team-001/coverage. 1063 / 1084 LOC (98.06%) covered.
> > One thing of note, is I also do
> > ```
> > bin/rails db:drop
> > bin/rails db:create
> > bin/rails db:migrate
> > bin/rails db:seed
> > ```
> 
> Wait I just tried again, I hadn't pulled correctly, now it also fails that test. Strange... Must have been introduced elsewhere.

I think what is happening is because it uses sample, only sometimes does it pick 0, which now is valid because we changed 0 to be okay as a quantity, just we don't let it show up. Nil and -1 still aren't valid so sometimes it suceeds. I think to fix it we just remove 0 from the list to sample.

2023-11-24 04:30 UTC, kesslerjohn commented on .gitignore
> +/coverage/*
Okay, I removed ths from .gitignore in [1e19164](https://github.com/uiowahjmjohnsonselt2023/selt2023-final-project-team-001/pull/30/commits/1e19164ab73d4761646763f72e4d31e279742134)

2023-11-24 04:45 UTC, kesslerjohn commented
Okay, rebasing is done. The relevant line in db/seeds/development.rb reads `quantity: Faker::Number.within(range: 0..100)` , which seems to resolve the problem. Rebasing is done - I'll make a comment in Teams too. Please take a look - no rush!

2023-11-24 23:09 UTC, blhohmann approved these changes
Great work! thanks for the changes

2023-11-24 23:10 UTC, merged