Storefront
uiowahjmjohnsonselt2023/selt2023-final-project-team-001 pull request #31
Opened 2023-11-23 11:35 UTC by blhohmann

# Pull Request: User Profile Feature

## Description

This pull request adds storefronts for registered sellers where they can advertise and link to their products. There are two ways to create a storefront, choosing from a premade template or by manually coding the html.

## Changes Made

Storefront Changes:
- View storefronts
- Create storefronts (manually code it, or choose from a premade template)
- Preview you manually coded storefront
- Save your manually coded storefront

General Changes:
- Fixed bug from checkout where firefox would get angry about potentially null values for expeditedShipping and regularShipping
 

## Usage and Testing

### To manually test the sign-in feature:
View Storefront links on nav bar and try to break it. If on a non seller account you will have to register for a seller before you can mess with it.

#### To run the rspec tests put this in your terminal
``` bundle exec rspec```

## Impact on Existing Code
- 1 breaking change. https://github.com/uiowahjmjohnsonselt2023/selt2023-final-project-team-001/compare/storefront?expand=1#diff-9802ca3c9c4cf89904fd44bc114e35ebdf2c5dd3d5b645491e2b253e1afef29bR27 there was two definitions for has_many :products. I suggested a fix in teams.

## Screenshots or Demos
### Include but are not limited to:
Home page nav bar sad path, not a seller so can't see storefront things
![image](https://github.com/uiowahjmjohnsonselt2023/selt2023-final-project-team-001/assets/112444260/b739f778-eb42-4b6c-a2ac-2db6dfc3d139)

Home page happy path, storefronts show for sellers
![image](https://github.com/uiowahjmjohnsonselt2023/selt2023-final-project-team-001/assets/112444260/9abd9962-d83c-4443-9267-107496cebd00)

Show happy path
![image](https://github.com/uiowahjmjohnsonselt2023/selt2023-final-project-team-001/assets/112444260/5a49ec03-3967-4a76-83ae-809e2dc9f63c)

Show sad path: needs to be implemented, just 404s

Choose template happy path:
![image](https://github.com/uiowahjmjohnsonselt2023/selt2023-final-project-team-001/assets/112444260/fdbec9d8-7e16-491d-916b-27d88198b30f)
![image](https://github.com/uiowahjmjohnsonselt2023/selt2023-final-project-team-001/assets/112444260/5b7a66cf-204b-47f3-9e7b-d631fce0ab2b)

Choose template happy path 2:
![image](https://github.com/uiowahjmjohnsonselt2023/selt2023-final-project-team-001/assets/112444260/9717ad8f-a94d-4e16-a91b-2960225332af)
![image](https://github.com/uiowahjmjohnsonselt2023/selt2023-final-project-team-001/assets/112444260/a9cc8299-bc06-4b23-8b29-d36d528e2381)

Manually add storefront happy path:
![image](https://github.com/uiowahjmjohnsonselt2023/selt2023-final-project-team-001/assets/112444260/5037a336-c305-4151-94bf-e3009c6cbc78)

Preview code happy path:
![image](https://github.com/uiowahjmjohnsonselt2023/selt2023-final-project-team-001/assets/112444260/6e5c2b56-810e-41fb-81ee-bca0e489b9b0)
![image](https://github.com/uiowahjmjohnsonselt2023/selt2023-final-project-team-001/assets/112444260/af8f5a8e-abaf-48d2-94a3-8edaf7b74761)

Save code happy path:
![image](https://github.com/uiowahjmjohnsonselt2023/selt2023-final-project-team-001/assets/112444260/6e5c2b56-810e-41fb-81ee-bca0e489b9b0)
![image](https://github.com/uiowahjmjohnsonselt2023/selt2023-final-project-team-001/assets/112444260/467db416-7841-4534-b80a-dfbbca8ded19)

## Additional Notes

- This feature is part of a feature requested by our contractor, wherein verified sellers can create storefronts
- I try to sanitize the manual code given, but I may have been to lenient or strict feel free to impugn that
- No major performance issues have been observed during testing.

## Reviewer Requests

I kindly request a review of these changes. Please provide feedback and suggestions. As this was a 5 point user story just 2 reviews will be necessary

## Status Checks and Tests

### Controller test
NOT YET TESTED I WILL UPDATE
```Coverage report generated for RSpec to /mnt/c/Users/blake/selt2023-final-project-team-001/coverage. 367 / 377 LOC (97.35%) covered.```

### Overall Tests
```Coverage report generated for RSpec to /mnt/c/Users/blake/selt2023-final-project-team-001/coverage. 591 / 605 LOC (97.69%) covered.```

## Discussion

Feel free to comment, ask questions, or provide feedback.

Should be no merge conflicts with main.

2023-11-23 17:07 UTC, powersaudrey25 commented on app/assets/javascripts/checkouts.js
thanks for catching this!

2023-11-23 17:12 UTC, powersaudrey25 commented on app/views/storefront/new_storefront_with_template.html.erb
> +<script>
Generally, I think it is preferred to keep your javascript in a js file and link it to your erb instead of including it directly. Not super important though

2023-11-24 05:25 UTC, blhohmann commented on app/views/storefront/new_storefront_with_template.html.erb
> +<script>
I'm having some difficulties with separating it unfortunately. I keep getting an error with document.currentScript is null in the browsers console. Would you mind helping me with this next Tuesday/whenever and then I will do a separate pull request. I think it would be a good idea for me to separate it.

2023-11-24 16:15 UTC, powersaudrey25 commented on app/controllers/storefronts_controller.rb
> +    respond_to do |format|
I tried just doing <h1>My Store</h1> and previewing worked but when I saved this is what I saw for the storefront. Not sure what would cause this yet 
<img width="500" alt="Screenshot 2023-11-24 at 10 14 01 AM" src="https://github.com/uiowahjmjohnsonselt2023/selt2023-final-project-team-001/assets/57544141/56447c64-9f4e-40f0-b1f5-e986d0c70907">

2023-11-24 16:20 UTC, powersaudrey25 commented on app/views/storefront/new_storefront_with_template.html.erb
> +<script>
Yeah for sure we can debug on tuesday

2023-11-24 16:22 UTC, powersaudrey25 commented
Pushed a fix for that failing product spec test

2023-11-24 16:23 UTC, powersaudrey25 commented
Other than that custom code bug(?), looks great, good work!

2023-11-24 17:47 UTC, kesslerjohn approved these changes
I don't have anything to add beyond what Audrey said. I'm getting the same bug when creating a custom storefront - other than that, it looks great! I'm approving since this bug isn't critical and I think we could get by just offering custom storefronts for this sprint if need be.

2023-11-24 18:30 UTC, blhohmann commented on app/controllers/storefronts_controller.rb
> +    respond_to do |format|
Thanks for letting me know, I'll look into that!

2023-11-24 19:11 UTC, blhohmann commented on app/controllers/storefronts_controller.rb
> +    respond_to do |format|
When I put in ```<h1>My Store</h1>``` I get this
![image](https://github.com/uiowahjmjohnsonselt2023/selt2023-final-project-team-001/assets/112444260/5325f9f2-f7a4-439a-b70d-06473b7e3ada)

Do you get any errors in the browsers console or in rubymine's terminal after you hit save?

2023-11-24 19:12 UTC, evfinkn requested changes
Good work, Blake! I have a couple of comments (some of which are kind of nitpicky, so I apologize 😅).

2023-11-24 19:12 UTC, evfinkn commented on spec/controllers/storefronts_controller_spec.rb
> +      end
I'm fine with pushing this for now because it's not a huge deal (and it's already in some of our other tests), but I think generally using `assigns` is bad practice (see its [deprecation issue](https://www.github.com/rails/rails/issues/18950)).

2023-11-24 19:12 UTC, evfinkn commented on spec/models/product_spec.rb
>      it "requires a quantity greater than 0" do
```suggestion
    it "requires a quantity greater than or equal to 0" do
```
Just a nitpick.

2023-11-24 19:12 UTC, evfinkn commented on spec/views/products/show.html.erb_spec.rb
> +RSpec.describe "products/new.html.erb", type: :view do
```suggestion
RSpec.describe "products/show.html.erb", type: :view do
```
I'm guessing this is a result of a RubyMine refactor. It should still be `"products/show.html.erb"` since that's the view the file name indicates is being tested.

2023-11-24 19:16 UTC, blhohmann commented on spec/controllers/storefronts_controller_spec.rb
> +      end
Interesting I didn't know that, next time I'll avoid using assigns, thanks.

2023-11-24 19:17 UTC, blhohmann commented on spec/views/products/show.html.erb_spec.rb
> +RSpec.describe "products/new.html.erb", type: :view do
Yep, either that or I copy pasted it and forgot to change it haha, good catch!

2023-11-24 19:20 UTC, blhohmann commented on app/views/application/_navbar.html.erb
> +        <% end %>
Will work on that next, probably better to save that navbar space I have used rn for later.

2023-11-24 19:31 UTC, powersaudrey25 commented on app/controllers/storefronts_controller.rb
> +    respond_to do |format|
No errors in the browser or in the terminal

2023-11-24 19:32 UTC, blhohmann commented on app/views/storefronts/new.html.erb
> +</div>
Commited o7.

2023-11-24 19:33 UTC, blhohmann commented on app/controllers/storefronts_controller.rb
> +    respond_to do |format|
Interesting, thanks for checking

2023-11-24 20:07 UTC, blhohmann commented on app/controllers/storefronts_controller.rb
> +    respond_to do |format|
Should be fixed, error was noticed by Evan, preview doesn't stay populated. So input code -> preview -> save without inputting again would save nothing.

2023-11-24 20:09 UTC, powersaudrey25 approved these changes

2023-11-24 20:53 UTC, evfinkn approved these changes
Looks good, thanks for the changes!

2023-11-24 23:12 UTC, evfinkn approved these changes

2023-11-25 00:34 UTC, merged