Reviews
uiowahjmjohnsonselt2023/selt2023-final-project-team-001 pull request #33
Opened 2023-11-23 21:38 UTC by powersaudrey25

temporary, just trying to resolve merge conflicts

2023-11-24 17:35 UTC, powersaudrey25 commented
I'm having trouble uploading UI pics but to test out these features you can:
Happy path:
1. Navigate to a seller's profile ( I used /profiles/2 )
2. Leave a review
3. fill out the fields

Sad path:
1. Navigate to a seller's profile
2. leave a a review
3. Change the profile id param to the current user's profile id 
4. Should be redirected to your profile with an error message

A user will not have a leave a review on their profile
A non seller will not have a leave a review on their profile
The seller rating will change based on the reviews (rating is rounded to nearest integer)

2023-11-24 23:59 UTC, blhohmann requested changes
Good job catching the leaving a review on your own profile.

Changes look good! Maybe in another iteration we could have something that lets you view all the reviews left on a seller

Just a few changes I think would help.

2023-11-24 23:59 UTC, blhohmann commented on app/views/reviews/new.html.erb
> +    <%= f.radio_button :answer, 0, label: "No", required: true, id: "no" %>
If you answer no, and give a rating it will say it succeeded without updating. I think the intended behavior is a flash mesage alert that is like "You can't leave a review if you haven't bought from this seller". In a future iteration we should check this in the db of orders, but thats a task for another day.
![image](https://github.com/uiowahjmjohnsonselt2023/selt2023-final-project-team-001/assets/112444260/27815908-8eca-4a84-8e08-d7ef568f6528)
![image](https://github.com/uiowahjmjohnsonselt2023/selt2023-final-project-team-001/assets/112444260/088c1095-855c-48a8-bc52-d322c844c433)

2023-11-24 23:59 UTC, blhohmann commented on app/controllers/reviews_controller.rb
> +    average_rating = (User.find params[:seller_id]).reviews_for_sellers.average(:interaction_rating).to_i
maybe we could make this @average_rating and display it in the profile show view? Unless I'm mistaken I don't think there is a way to view this through the ui

2023-11-24 23:59 UTC, blhohmann commented on app/controllers/reviews_controller.rb
> +    if Current.user.id == @seller_id.to_i
There also should be a check here for something unless User.findby(@seller_id).is_seller then give a flash for "You cannot leave a review for a non-seller. Right now I can leave a review for a buyer by manually changing the url, kinda like how without this line you had you could leave a review for yourself.

2023-11-24 23:59 UTC, blhohmann commented on app/controllers/reviews_controller.rb
> +    average_rating = (User.find params[:seller_id]).reviews_for_sellers.average(:interaction_rating).to_i
Maybe disregard, is the average what is displayed rn, I might have misinterpreted and thought it was the most recent review. If this is true ignore my comment.

2023-11-25 00:02 UTC, powersaudrey25 commented on app/views/reviews/new.html.erb
> +    <%= f.radio_button :answer, 0, label: "No", required: true, id: "no" %>
I see what you mean. I was thinking that a user didn't have to necessarily buy from someone, maybe they messaged them and had a bad/good interaction that way.

2023-11-25 00:03 UTC, powersaudrey25 commented on app/controllers/reviews_controller.rb
> +    average_rating = (User.find params[:seller_id]).reviews_for_sellers.average(:interaction_rating).to_i
The average is what is displayed for the seller_rating, sorry I probably could've worded that better!

2023-11-25 00:03 UTC, powersaudrey25 commented on app/controllers/reviews_controller.rb
> +    if Current.user.id == @seller_id.to_i
Good catch, I will implement that quick

2023-11-25 00:36 UTC, powersaudrey25 commented on app/views/reviews/new.html.erb
> +    <%= f.radio_button :answer, 0, label: "No", required: true, id: "no" %>
looks like I accidentally only allowed for true values for the has purchased from, pushed a change to allow for true and false

2023-11-25 00:36 UTC, powersaudrey25 commented on app/controllers/reviews_controller.rb
> +    if Current.user.id == @seller_id.to_i
pushed a change to implement that

2023-11-25 00:36 UTC, blhohmann commented on app/views/reviews/new.html.erb
> +    <%= f.radio_button :answer, 0, label: "No", required: true, id: "no" %>
Oh that makes sense then I think. I'm fine with leaving it as is then.

2023-11-25 00:37 UTC, blhohmann commented on app/controllers/reviews_controller.rb
> +    average_rating = (User.find params[:seller_id]).reviews_for_sellers.average(:interaction_rating).to_i
No worries

2023-11-25 00:42 UTC, blhohmann approved these changes
changes all appear to be working correctly upon checkout and running, thanks for the changes.

2023-11-25 01:19 UTC, merged