feat: create Product model
uiowahjmjohnsonselt2023/selt2023-final-project-team-001 pull request #5
Opened 2023-11-08 04:21 UTC by evfinkn

- Create `Product` model
- Create `Category` model for use in `Product`
- Add categories to db/seeds.rb
- Add money-rails gem to make handling money easier (e.g., for `Product#price`)

2023-11-08 18:30 UTC, blhohmann commented
It might be helpful to add seeding for a few products in general rather than just categories in seeds.rb.

2023-11-09 00:21 UTC, blhohmann requested changes

2023-11-09 05:54 UTC, evfinkn commented on app/models/product.rb
> +  belongs_to :category
I agree. I've updated this, but I used `has_many :through` instead of `has_and_belongs_to_many` since the former can be easily extended in the future if needed.

2023-11-09 05:58 UTC, evfinkn commented on db/seeds.rb
> +categories.each do |category|
Originally, I didn't include any dummy data since I think seeds.rb is for creating data that has to be (or is assumed to be) in the database. However, I found a nice way to conditionally seed depending on the environment, so now dummy data is created for the development database.

2023-11-09 14:00 UTC, blhohmann approved these changes
Looks great! Thanks for the changes.

2023-11-09 14:21 UTC, merged