Deals
uiowahjmjohnsonselt2023/selt2023-final-project-team-001 pull request #65
Opened 2023-12-09 22:31 UTC by evfinkn

Checkout page showing discounts (Practical Plastic Car has a 50% off discount):

![Screenshot 2023-12-09 at 16-30-07 Selt2023FinalProjectTeam001](https://github.com/uiowahjmjohnsonselt2023/selt2023-final-project-team-001/assets/6924485/67a9d586-bd40-412b-96b7-0c3288e2b09d)

2023-12-09 22:39 UTC, blhohmann requested changes
Haven't looked over everything, just a comment about how this should interact with my merged PR of price_alerts

2023-12-09 22:39 UTC, blhohmann commented on app/models/promotion.rb
> +    started? && !ended?
Do you have this working with price_alerts, rn price alerts only checks when a price is manually updated (see here https://github.com/uiowahjmjohnsonselt2023/selt2023-final-project-team-001/blob/0d139671700150c07a339b35543722b58721bd0f/app/controllers/products_controller.rb#L98-L109)

If this doesn't work with price alerts, maybe you could throw something like that code here, where if the deal is active and the price is lower than any price alert thresholds, send the email and delete the price alert?

2023-12-10 09:26 UTC, blhohmann requested changes
Other thing is we will need to add this to the user dropdown and rebase. Looks great!

2023-12-10 09:26 UTC, blhohmann commented on app/models/promotion.rb
> +
```suggestion
  validates :product_ids, presence: true
```
This makes it so you can't create a promotion without selecting a product to include.

2023-12-10 09:26 UTC, blhohmann commented on app/views/products/show.html.erb
We should probably have something here to show a deal exists on the product, before we get to the checkout. I'll play around and see if I can get a suggestion.

2023-12-10 09:58 UTC, evfinkn commented on app/models/promotion.rb
> +
Actually this is intentional. Promotions without products selected will apply to all of the seller's products. I'll add a note on the form 🫡

2023-12-10 10:17 UTC, blhohmann approved these changes
Great changes, good work looks cool!

2023-12-10 10:32 UTC, powersaudrey25 approved these changes

2023-12-10 10:33 UTC, merged